import type { Metadata } from 'next'
import { Raleway, Montserrat, Inter } from 'next/font/google'
import './globals.css'

const raleway = Raleway({ subsets: ['latin'] })
export const montserrat = Montserrat({ subsets: ['latin'] })
export const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={raleway.className}>
        <main className='max-w-[1440px] min-h-[1362px] xs:min-h-[1598px] w-screen mx-auto'>
          {children}
        </main>
      </body>
    </html>
  )
}
